[package]
name = "qray"
version = "0.1.0"
authors = ["harukitosa <13haruki28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14"
num-complex = "0.4"
ndarray-rand = "0.14.0"
rand = "0.6"